# frozen_string_literal: true

source "https://rubygems.org"

gem "aasm", "~> 5.0", ">= 5.0.1"
gem "active_model_serializers", "~> 0.10.0"
gem "activerecord_json_validator", "~> 1.3"
gem "apollo-federation", "1.1.3"
gem "audited", "~> 4.8"
gem "aws-sdk-s3", require: false
gem "aws-sdk-sqs", "~> 1.3"
gem "base32-url", "~> 0.3"
gem "batch-loader", "~> 1.4", ">= 1.4.1"
gem "bcrypt", "~> 3.1.7"
gem "bolognese", "~> 2.0.2"
gem "bootsnap", "~> 1.4", ">= 1.4.4", require: false
gem "cancancan", "~> 3.0"
gem "commonmarker", "~> 0.23.4"
gem "countries", "~> 2.1", ">= 2.1.2"
gem "country_select", "~> 3.1"
gem "crawler_detect"
gem "dalli", "~> 2.7", ">= 2.7.6"
gem "ddtrace", "~> 0.32.0"
gem "departure", "~> 6.2"
gem "diffy", "~> 3.2", ">= 3.2.1"
gem "dotenv"
gem "elasticsearch", "7.5"
gem "elasticsearch-model", "~> 7.1.1", ">= 7.1.1", require: "elasticsearch/model"
gem "elasticsearch-rails", "~> 7.1.1", ">= 7.1.1"
gem "elasticsearch-transport", "7.5"
gem "equivalent-xml", "~> 0.6.0"
gem "facets", require: false
gem "faraday", "~> 0.17.3"
gem "faraday_middleware-aws-sigv4", "~> 0.3.0"
gem "fast_jsonapi", "~> 1.3"
gem "flipper", "~> 0.17.0"
gem "flipper-active_support_cache_store"
gem "gender_detector", "~> 0.1.2"
gem "git", "~> 1.11"
gem "google-protobuf", "3.19.6"
gem "graphql", "1.11.4"
gem "graphql-batch", "~> 0.4.1"
gem "graphql-cache", "~> 0.6.0"
gem "graphql-errors", "~> 0.4.0"
gem "hashid-rails", "~> 1.4"
gem "iso-639", "~> 0.3.5"
gem "iso8601", "~> 0.9.0"
gem "jsonlint", "~> 0.3.0"
gem "jwt"
gem "kaminari", "~> 1.2"
gem "kt-paperclip", "~> 6.2", ">= 6.2.2"
gem "lograge", "~> 0.11.2"
gem "logstash-event", "~> 1.2", ">= 1.2.02"
gem "logstash-logger", "~> 0.26.1"
gem "mailgun-ruby", "~> 1.1", ">= 1.1.8"
gem "maremma", "~> 4.9.6"
gem "mini_magick", "~> 4.8"
gem "mysql2", "~> 0.5.3"
gem "nokogiri", ">= 1.11.2"
gem "oj", ">= 2.8.3"
gem "oj_mimic_json", "~> 1.0", ">= 1.0.1"
gem "premailer", "~> 1.11", ">= 1.11.1"
gem "pwqgen.rb", "~> 0.1.0"
gem "rack-cors", "~> 1.0", require: "rack/cors"
gem "rack-utf8_sanitizer", "~> 1.6"
gem "rails", "~> 6.1.7"
gem "rake", "~> 12.0"
gem "sentry-raven", "~> 2.9"
gem "shoryuken", "~> 4.0"
gem "simple_command"
gem "slack-notifier", "~> 2.1"
gem "sparql", "~> 3.1", ">= 3.1.2"
gem "sprockets", "~> 3.7", ">= 3.7.2"
gem "string_pattern"
gem "strip_attributes", "~> 1.8"
gem "turnout", "~> 2.5"
gem "uuid", "~> 2.3", ">= 2.3.9"
gem "mimemagic", "0.3.10"

group :development, :test do
  gem "better_errors"
  gem "binding_of_caller"
  gem "bullet", "~> 6.1"
  gem "byebug", platforms: %i[mri mingw x64_mingw]
  gem "rspec-benchmark", "~> 0.4.0"
  gem "rspec-graphql_matchers", "~> 1.1"
  gem "rspec-rails", "~> 3.8", ">= 3.8.2"
  gem "rubocop", "~> 1.3", ">= 1.3.1"
  gem "rubocop-performance", "~> 1.5", ">= 1.5.1"
  gem "rubocop-rails", "~> 2.8", ">= 2.8.1"
  gem "rubocop-packaging", "~> 0.5.1"
  gem "rubocop-rspec", "~> 2.0", require: false
end

group :development do
  gem "listen", ">= 3.0.5", "< 3.2"
  gem "seedbank"
  gem "spring"
  gem "spring-commands-rspec"
  gem "spring-watcher-listen", "~> 2.0.0"
  # gem "httplog", "~> 1.0"
end

group :test do
  gem "capybara"
  gem "database_cleaner"
  gem "elasticsearch-extensions", "~> 0.0.29"
  gem "factory_bot_rails", "~> 4.8", ">= 4.8.2"
  gem "faker", "~> 1.9"
  gem "hashdiff", [">= 1.0.0.beta1", "< 2.0.0"]
  gem "shoulda-matchers", "~> 4.1", ">= 4.1.2"
  gem "simplecov", "~> 0.17.1"
  gem "test-prof", "~> 0.10.2"
  gem "vcr", "~> 5.1"
  gem "webmock", "~> 3.1"
  gem "parallel_tests", "~> 3.12"
end
