mysql: &mysql
  adapter: mysql2

defaults: &defaults
  pool: <%= ENV['CONCURRENCY'].to_i + 5 %>
  timeout: 5000
  wait_timeout: 1800
  encoding: utf8mb4
  username: <%= ENV['MYSQL_USER'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  database: <%= ENV['MYSQL_DATABASE'] %>
  host: <%= ENV['MYSQL_HOST'] %>
  port: <%= ENV['MYSQL_PORT'] %>

  <<: *mysql

development:
  <<: *defaults

test:
  <<: *defaults
  database: <%= ENV['MYSQL_DATABASE'] %>_test<%= ENV['TEST_ENV_NUMBER'] %>

production:
  <<: *defaults

stage:
  <<: *defaults

uat:
  <<: *defaults
