concurrency: <%= ENV.fetch('SHORYUKEN_CONCURRENCY', 15) %>
delay: 0
pidfile: tmp/pids/shoryuken.pid
queues:
  - [lupo, 8]
  - [lupo_import, 8]
  - [lupo_import_other_doi, 8]
  - [lupo_transfer, 4]
  - [lupo_background, 2]
