name: RuboCop

on:
  workflow_call:
    inputs:
      run_gem_audit:
        description: 'Run bundler-audit security check'
        type: boolean
        default: false
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUNDLE_WITHOUT: "default doc job cable storage ujs test db"
      BUNDLE_PATH: "vendor/bundle"
    steps:
    - uses: actions/checkout@v5
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 4.0.1
        bundler-cache: true
    - name: Run RuboCop
      run: bundle exec rubocop --parallel
    - name: Security Check (bundler-audit)
      if: inputs.run_gem_audit
      run: bundle exec bundler-audit check --update
    - name: Security Check (brakeman)
      run: bundle exec brakeman --no-pager
